name: Lint and Test Charts

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@main
        with:
          command: lint
          config: .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.22.17
          - v1.23.17
          - v1.24.13
          - v1.25.8
          - v1.26.3
          - v1.27.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  # install-chart:
  #   name: install-chart
  #   runs-on: ubuntu-latest
  #   needs:
  #     - lint-chart
  #     - lint-docs
  #     - kubeval-chart
  #   strategy:
  #     matrix:
  #       k8s:
  #         - v1.12.10
  #         - v1.13.12
  #         - v1.14.10
  #         - v1.15.7
  #         - v1.16.4
  #         - v1.17.2
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Create kind ${{ matrix.k8s }} cluster
  #       uses: helm/kind-action@main
  #       with:
  #         node_image: kindest/node:${{ matrix.k8s }}
  #     - name: Run chart-testing (install)
  #       uses: helm/chart-testing-action@main
  #       with:
  #         command: install
  #         config: .github/ct.yaml
