name: Release Charts

on:
  push:
    branches:
      - gha
    # paths:
    #   - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        # gh-pages is the branch where this will be published, not configurable
        uses: helm/chart-releaser-action@main
        with:
          charts_dir: charts
        env:
          CR_TOKEN: '${{ secrets.CR_TOKEN }}'
