# This action will only create a release (e.g. actinia-1.1.5) in case a release
# with current chart version does not exist yet. Then also index.yaml will be
# updated in gh-pages branch

name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        # gh-pages is the branch where this will be published, not configurable
        uses: helm/chart-releaser-action@main
        with:
          charts_dir: charts
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
